paths:
  skills_dir: skills
  workflows_dir: configs/workflows
  runs_dir: runs
  state_dir: state

budgets:
  max_steps: 300
  max_skill_calls: 300
  max_environment_calls: 300

planner:
  backend: llm
  llm:
    provider: openai_compatible
    base_url: "http://s-20260414130351-jjtwx-decode.ailab-safethm.svc:22372/v1" # qwen35 http://s-20260414130351-jjtwx-decode.ailab-safethm.svc:22372/v1 ｜ oss http://s-20260330192936-zlwm5-decode.ailab-safethm.svc:23297/v1
    model: "orm"
    api_key: "FAKE_API_KEY"
    timeout_seconds: 8
    temperature: 0.1
    max_tokens: 6000
    fallback_to_rule_based: true

meta_skills:
  backend: llm
  llm:
    provider: openai_compatible
    enabled: true
    inherit_planner_endpoint: true
    base_url: "http://s-20260414130351-jjtwx-decode.ailab-safethm.svc:22372/v1"
    model: "orm"
    api_key: "FAKE_API_KEY"
    timeout_seconds: 12
    temperature: 0.2
    max_tokens: 1200
    fallback_to_template: true

skills:
  backend: llm
  llm:
    provider: openai_compatible
    enabled: true
    inherit_planner_endpoint: true
    base_url: "http://s-20260414130351-jjtwx-decode.ailab-safethm.svc:22372/v1"
    model: "orm"
    api_key: "FAKE_API_KEY"
    timeout_seconds: 12
    temperature: 0.9
    max_tokens: 2048

evaluator:
  backend: composite
  guard_model:
    enabled: true
    base_url: "http://s-20251119153749-lp69w-decode.ailab-safethm.svc:23344/v1"
    model: "orm"
    api_key: "FAKE_API_KEY"
    transport: "openai_sdk"
    include_system_prompt: false
    send_sampling_params: true
    timeout_seconds: 8
    temperature: 0.0
    top_p: 1.0
    max_tokens: 800
    fallback_to_heuristic: true

environment:
  backend: llm
  target_profile:
    model_name: mock-target-model
    mode: sandbox
  llm:
    provider: openai_compatible
    enabled: true
    base_url: "http://s-20260304150204-6bjfm-decode.ailab-safethm.svc:22103/v1" # "http://s-20260304150204-6bjfm-decode.ailab-safethm.svc:22103/v1" # "https://api.boyuerichdata.opensphereai.com/v1"
    model: "orm" # "orm" # "gemini-2.5-flash"
    api_key: "FAKE_API_KEY" # "FAKE_API_KEY"
    transport: "openai_sdk"
    include_system_prompt: false
    send_sampling_params: true
    timeout_seconds: 12
    temperature: 0.0
    top_p: 1.0
    max_tokens: 2048
    fallback_to_mock: true

defaults:
  workflow: basic
  recent_memory_window: 5
